name : Download Artifact
on : push
jobs:
    runs-on: redhat-linux-2022
    steps:
     - name: Upload Artifact
    uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: src
